#!/bin/bash -eu

function faketty { script -qfc "$(printf "%q " "$@")" /dev/null; }

# Run the ag command in a fake TTY and sort the output.
# This will let us get predictable results, and quickly.
faketty ag --nocolor --nogroup --hidden --line-numbers --filename \
    --ignore=.git --ignore=.svn --ignore=.hg --ignore=.bzr \
    "$@" | sort
